### ISSUE TITLE
Readme headers need a space between "#" and the header

### ISSUE THREAD

**Issue by shadiakiki1986** [minerva22/ffa-jobs-emails#3]
For example, 
```
#Fix issue: django.db.utils.IntegrityError: NOT NULL constraint failed:
```
can be
```
# Fix issue
django.db.utils.IntegrityError: NOT NULL constraint failed:
```
This makes the front page of your project in github look nicer

**Comment by minerva22** [comment]
done

**Comment by shadiakiki1986** [comment]
I don't see how this is done. Your [home page](https://github.com/minerva22/jobsproj) still doesn't have proper headers displayed.
